# 가장 기본이 되는 db와 kafka broker를 띄우는 docker-compose

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ssafynews
      POSTGRES_PASSWORD: ssafynews13
      POSTGRES_DB: news
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:latest
    container_name: brocker
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0                                         # 노드 ID
      - KAFKA_CFG_PROCESS_ROLES=broker,controller                   # broker와 controller 역할
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093         # 컨트롤러가 자기 자신에게 투표
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093    # 브로커용(9092), 컨트롤러용(9093) 리스너 등록
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092   # 외부에서 접근할 때 사용할 주소
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER              # 컨트롤러 리스너 지정
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT              # 브로커 간 통신 리스너 지정
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true                    # 자동으로 토픽 생성